/**
 * Модуль экспорта 3D-моделей в различные форматы
 *
 * Поддерживает экспорт в форматы:
 * - OBJ (Wavefront) + MTL - широкая совместимость с 3ds Max
 * - GLTF/GLB - современный формат для веба и 3ds Max 2021+
 *
 * @module ModelExporter
 */

import * as THREE from 'three';
import { ExportSettings, ModelInfo } from '../types/building';

/**
 * Класс для экспорта 3D-моделей
 *
 * Генерирует файлы форматов OBJ и GLTF непосредственно в браузере,
 * без использования серверной обработки.
 */
export class ModelExporter {
    private scene: THREE.Object3D;

    constructor(scene: THREE.Object3D) {
        this.scene = scene;
    }

    /**
     * Экспорт в формат OBJ (Wavefront)
     *
     * OBJ - универсальный формат, поддерживаемый всеми версиями 3ds Max.
     * Создает два файла: .obj (геометрия) и .mtl (материалы)
     *
     * @param filename - Имя файла без расширения
     * @param scale - Масштаб модели (по умолчанию 1:1, единицы = метры)
     */
    public exportOBJ(filename: string = 'building', scale: number = 1): void {
        const objData = this.generateOBJ(scale);
        const mtlData = this.generateMTL(filename);

        // Скачиваем OBJ файл
        this.downloadFile(`${filename}.obj`, objData, 'model/obj');

        // Скачиваем MTL файл
        this.downloadFile(`${filename}.mtl`, mtlData, 'model/mtl');
    }

    /**
     * Генерация содержимого OBJ файла
     *
     * Формат OBJ - текстовый формат, где:
     * - v x y z - вершины
     * - vn x y z - нормали
     * - vt u v - текстурные координаты
     * - f v/vt/vn - грани
     * - usemtl name - ссылка на материал
     * - g name - группа объектов
     */
    private generateOBJ(scale: number): string {
        const output: string[] = [];
        const vertices: string[] = [];
        const normals: string[] = [];
        const uvs: string[] = [];
        const faces: string[] = [];

        let vertexOffset = 1; // OBJ индексы начинаются с 1
        let normalOffset = 1;
        let uvOffset = 1;

        // Заголовок файла
        output.push('# Parametric Architecture Model');
        output.push('# Generated by Three.js Parametric Building Generator');
        output.push(`# Scale: 1 unit = ${scale} meter(s)`);
        output.push('# Compatible with Autodesk 3ds Max');
        output.push('');
        output.push(`mtllib building.mtl`);
        output.push('');

        // Обход всех мешей в сцене
        this.scene.traverse((object) => {
            if (object instanceof THREE.Mesh) {
                const geometry = object.geometry;
                const material = object.material as THREE.Material;

                if (!(geometry instanceof THREE.BufferGeometry)) return;

                // Получаем мировую матрицу трансформации
                object.updateMatrixWorld(true);
                const worldMatrix = object.matrixWorld;
                const normalMatrix = new THREE.Matrix3().getNormalMatrix(worldMatrix);

                // Название группы
                const groupName = object.name || 'object_' + object.id;
                output.push(`g ${groupName}`);
                output.push(`usemtl ${this.getMaterialName(material)}`);

                // Позиции вершин
                const positionAttr = geometry.getAttribute('position');
                const normalAttr = geometry.getAttribute('normal');
                const uvAttr = geometry.getAttribute('uv');
                const indexAttr = geometry.getIndex();

                // Обрабатываем вершины
                if (positionAttr) {
                    for (let i = 0; i < positionAttr.count; i++) {
                        const vertex = new THREE.Vector3(
                            positionAttr.getX(i),
                            positionAttr.getY(i),
                            positionAttr.getZ(i)
                        );
                        // Применяем мировую трансформацию и масштаб
                        vertex.applyMatrix4(worldMatrix);
                        vertex.multiplyScalar(scale);

                        vertices.push(`v ${vertex.x.toFixed(6)} ${vertex.y.toFixed(6)} ${vertex.z.toFixed(6)}`);
                    }
                }

                // Обрабатываем нормали
                if (normalAttr) {
                    for (let i = 0; i < normalAttr.count; i++) {
                        const normal = new THREE.Vector3(
                            normalAttr.getX(i),
                            normalAttr.getY(i),
                            normalAttr.getZ(i)
                        );
                        normal.applyMatrix3(normalMatrix).normalize();
                        normals.push(`vn ${normal.x.toFixed(6)} ${normal.y.toFixed(6)} ${normal.z.toFixed(6)}`);
                    }
                }

                // Обрабатываем UV координаты
                if (uvAttr) {
                    for (let i = 0; i < uvAttr.count; i++) {
                        uvs.push(`vt ${uvAttr.getX(i).toFixed(6)} ${uvAttr.getY(i).toFixed(6)}`);
                    }
                }

                // Обрабатываем грани
                if (indexAttr) {
                    for (let i = 0; i < indexAttr.count; i += 3) {
                        const a = indexAttr.getX(i) + vertexOffset;
                        const b = indexAttr.getX(i + 1) + vertexOffset;
                        const c = indexAttr.getX(i + 2) + vertexOffset;

                        if (uvAttr && normalAttr) {
                            const aUV = indexAttr.getX(i) + uvOffset;
                            const bUV = indexAttr.getX(i + 1) + uvOffset;
                            const cUV = indexAttr.getX(i + 2) + uvOffset;
                            const aN = indexAttr.getX(i) + normalOffset;
                            const bN = indexAttr.getX(i + 1) + normalOffset;
                            const cN = indexAttr.getX(i + 2) + normalOffset;
                            faces.push(`f ${a}/${aUV}/${aN} ${b}/${bUV}/${bN} ${c}/${cUV}/${cN}`);
                        } else if (normalAttr) {
                            const aN = indexAttr.getX(i) + normalOffset;
                            const bN = indexAttr.getX(i + 1) + normalOffset;
                            const cN = indexAttr.getX(i + 2) + normalOffset;
                            faces.push(`f ${a}//${aN} ${b}//${bN} ${c}//${cN}`);
                        } else {
                            faces.push(`f ${a} ${b} ${c}`);
                        }
                    }
                } else if (positionAttr) {
                    // Без индексов
                    for (let i = 0; i < positionAttr.count; i += 3) {
                        const a = i + vertexOffset;
                        const b = i + 1 + vertexOffset;
                        const c = i + 2 + vertexOffset;

                        if (normalAttr) {
                            faces.push(`f ${a}//${a - vertexOffset + normalOffset} ${b}//${b - vertexOffset + normalOffset} ${c}//${c - vertexOffset + normalOffset}`);
                        } else {
                            faces.push(`f ${a} ${b} ${c}`);
                        }
                    }
                }

                // Обновляем смещения
                if (positionAttr) vertexOffset += positionAttr.count;
                if (normalAttr) normalOffset += normalAttr.count;
                if (uvAttr) uvOffset += uvAttr.count;

                output.push('');
            }
        });

        // Собираем файл
        return [
            ...output.slice(0, output.indexOf('') + 1),
            ...vertices,
            '',
            ...normals,
            '',
            ...uvs,
            '',
            ...output.slice(output.indexOf('') + 1),
            ...faces
        ].join('\n');
    }

    /**
     * Генерация содержимого MTL файла (материалы)
     *
     * MTL формат описывает материалы:
     * - newmtl name - определение материала
     * - Ka r g b - ambient цвет
     * - Kd r g b - diffuse цвет
     * - Ks r g b - specular цвет
     * - Ns value - shininess
     * - d value - прозрачность
     */
    private generateMTL(filename: string): string {
        const output: string[] = [];
        const processedMaterials = new Set<string>();

        output.push('# Material Library');
        output.push(`# Generated for ${filename}.obj`);
        output.push('');

        this.scene.traverse((object) => {
            if (object instanceof THREE.Mesh) {
                const material = object.material as THREE.MeshStandardMaterial;
                const materialName = this.getMaterialName(material);

                if (processedMaterials.has(materialName)) return;
                processedMaterials.add(materialName);

                output.push(`newmtl ${materialName}`);

                // Получаем цвет материала
                const color = material.color || new THREE.Color(0xcccccc);
                output.push(`Ka ${(color.r * 0.2).toFixed(4)} ${(color.g * 0.2).toFixed(4)} ${(color.b * 0.2).toFixed(4)}`);
                output.push(`Kd ${color.r.toFixed(4)} ${color.g.toFixed(4)} ${color.b.toFixed(4)}`);

                // Specular
                const specular = 0.3;
                output.push(`Ks ${specular.toFixed(4)} ${specular.toFixed(4)} ${specular.toFixed(4)}`);

                // Shininess (преобразуем roughness в shininess)
                const roughness = material.roughness !== undefined ? material.roughness : 0.5;
                const shininess = Math.max(1, (1 - roughness) * 100);
                output.push(`Ns ${shininess.toFixed(2)}`);

                // Прозрачность
                const opacity = material.opacity !== undefined ? material.opacity : 1;
                output.push(`d ${opacity.toFixed(4)}`);

                // Модель освещения
                output.push('illum 2');

                output.push('');
            }
        });

        return output.join('\n');
    }

    /**
     * Получение имени материала
     */
    private getMaterialName(material: THREE.Material): string {
        if (material.name) return material.name.replace(/\s+/g, '_');

        const stdMat = material as THREE.MeshStandardMaterial;
        if (stdMat.color) {
            return `material_${stdMat.color.getHexString()}`;
        }
        return `material_${material.id}`;
    }

    /**
     * Экспорт в формат GLTF
     *
     * GLTF - современный формат, поддерживаемый 3ds Max 2021+
     * Включает геометрию, материалы и текстуры в одном файле (GLB)
     * или раздельно (GLTF + BIN + текстуры)
     */
    public async exportGLTF(filename: string = 'building', binary: boolean = true): Promise<void> {
        // Динамически импортируем GLTFExporter
        const { GLTFExporter } = await import('three/addons/exporters/GLTFExporter.js');

        const exporter = new GLTFExporter();

        const options = {
            binary: binary, // GLB или GLTF
            trs: false,
            onlyVisible: true,
            truncateDrawRange: false,
            maxTextureSize: 4096,
        };

        exporter.parse(
            this.scene,
            (result) => {
                if (result instanceof ArrayBuffer) {
                    // GLB (бинарный)
                    this.downloadFile(
                        `${filename}.glb`,
                        result,
                        'model/gltf-binary'
                    );
                } else {
                    // GLTF (JSON)
                    const jsonString = JSON.stringify(result, null, 2);
                    this.downloadFile(
                        `${filename}.gltf`,
                        jsonString,
                        'model/gltf+json'
                    );
                }
            },
            (error) => {
                console.error('GLTF Export Error:', error);
                alert('Ошибка экспорта в GLTF: ' + error.message);
            },
            options
        );
    }

    /**
     * Скачивание файла
     */
    private downloadFile(filename: string, data: string | ArrayBuffer, mimeType: string): void {
        let blob: Blob;

        if (data instanceof ArrayBuffer) {
            blob = new Blob([data], { type: mimeType });
        } else {
            blob = new Blob([data], { type: mimeType });
        }

        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = filename;
        link.click();

        // Очищаем URL
        setTimeout(() => URL.revokeObjectURL(url), 100);
    }

    /**
     * Получение данных для отправки на сервер
     *
     * Возвращает Blob с данными модели для загрузки через API
     */
    public async getExportData(format: 'obj' | 'gltf' | 'glb'): Promise<{
        file: Blob;
        materialFile?: Blob;
        info: ModelInfo;
    }> {
        const info = this.getModelInfo();

        if (format === 'obj') {
            const objData = this.generateOBJ(1);
            const mtlData = this.generateMTL('building');

            return {
                file: new Blob([objData], { type: 'model/obj' }),
                materialFile: new Blob([mtlData], { type: 'model/mtl' }),
                info,
            };
        }

        // GLTF/GLB
        return new Promise(async (resolve, reject) => {
            const { GLTFExporter } = await import('three/addons/exporters/GLTFExporter.js');
            const exporter = new GLTFExporter();

            exporter.parse(
                this.scene,
                (result) => {
                    if (result instanceof ArrayBuffer) {
                        resolve({
                            file: new Blob([result], { type: 'model/gltf-binary' }),
                            info,
                        });
                    } else {
                        resolve({
                            file: new Blob([JSON.stringify(result)], { type: 'model/gltf+json' }),
                            info,
                        });
                    }
                },
                reject,
                { binary: format === 'glb' }
            );
        });
    }

    /**
     * Получение информации о модели
     */
    private getModelInfo(): ModelInfo {
        let verticesCount = 0;
        let facesCount = 0;

        this.scene.traverse((object) => {
            if (object instanceof THREE.Mesh) {
                const geometry = object.geometry;
                if (geometry instanceof THREE.BufferGeometry) {
                    const position = geometry.getAttribute('position');
                    if (position) {
                        verticesCount += position.count;
                    }
                    const index = geometry.getIndex();
                    if (index) {
                        facesCount += index.count / 3;
                    } else if (position) {
                        facesCount += position.count / 3;
                    }
                }
            }
        });

        // Получаем высоту из bounding box
        const box = new THREE.Box3().setFromObject(this.scene);
        const totalHeight = box.max.y - box.min.y;

        return {
            verticesCount,
            facesCount: Math.round(facesCount),
            totalHeight,
        };
    }
}

/**
 * Информация о совместимости форматов с 3ds Max
 *
 * OBJ формат:
 * - Поддерживается всеми версиями 3ds Max
 * - При импорте: File -> Import -> Select Files
 * - Настройки импорта: включить "Import as single mesh" для объединения
 * - Единицы измерения: метры (1 unit = 1 meter)
 * - Ограничения: не поддерживает анимацию, нет PBR материалов
 *
 * GLTF/GLB формат:
 * - Поддерживается в 3ds Max 2021 и новее
 * - Требуется плагин для более ранних версий
 * - Поддерживает PBR материалы
 * - При импорте материалы автоматически конвертируются
 * - Рекомендуется для современных проектов
 *
 * Рекомендации:
 * 1. Для совместимости со старыми версиями используйте OBJ
 * 2. Для современных проектов с PBR используйте GLTF
 * 3. Проверяйте единицы измерения при импорте (System Unit Setup)
 * 4. Для архитектурных моделей рекомендуется масштаб 1:1 (метры)
 */
export const FORMAT_COMPATIBILITY = {
    obj: {
        name: 'Wavefront OBJ',
        extension: '.obj',
        maxVersions: 'Все версии',
        features: ['Геометрия', 'Базовые материалы', 'UV координаты'],
        limitations: ['Нет PBR', 'Нет анимации', 'Отдельный файл материалов'],
    },
    gltf: {
        name: 'GLTF 2.0',
        extension: '.gltf',
        maxVersions: '3ds Max 2021+',
        features: ['Геометрия', 'PBR материалы', 'Текстуры', 'Анимация'],
        limitations: ['Требует новую версию 3ds Max'],
    },
    glb: {
        name: 'GLB (Binary GLTF)',
        extension: '.glb',
        maxVersions: '3ds Max 2021+',
        features: ['Все в одном файле', 'PBR материалы', 'Компактный размер'],
        limitations: ['Требует новую версию 3ds Max'],
    },
};
